services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ecommerce_auth'
      - 'POSTGRES_PASSWORD=authAdmin1234'
      - 'POSTGRES_USER=admin'
    ports:
      - '5434:5432'
