services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ecommerce_email'
      - 'POSTGRES_PASSWORD=emailAdmin1234'
      - 'POSTGRES_USER=admin'
    ports:
      - '5435:5432'
